[general]
# Adwaita [GTK3] theme is default. Also I fucking love this theme.

[font]
normal = { family = "MononokiNerdFont", style = "Regular" }
size = 12.0

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[window]
opacity = 0.8
padding = { x = 2, y = 2 }
